repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy llm_stream
        language: system
        types: [python]
        # use require_serial so that script
        # is only called once per commit
        require_serial: true
        pass_filenames: false
